modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Command17/EnchantedBookLib/issues"
license = "MIT"

[[mods]]
modId = "enchantedbooklib"
version = "${version}"
displayName = "EnchantedBookLib"
authors = "Command17"
description = '''
A library mod for making multiplatform modding just a bit easier.
'''
logoFile = "assets/enchantedbooklib/icon.png"

[[dependencies.enchantedbooklib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchantedbooklib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "enchantedbooklib-common.mixins.json"

[[mixins]]
config = "enchantedbooklib-neoforge.mixins.json"